---
title: "GENOVA: explore the Hi-C's"
author: "Robin H van der Weide"
date: "27 October 2016"
output: 
  rmarkdown::html_vignette
---
```{r}
library(GENOVA)
```

# Set up experiments 

---

### Construct experiment-objects
```{r load, cache=T, cache.lazy=F, message=F, warning=F, results=F}
ptm <- proc.time()
Rao_20k <- construct.experiment(ICEDpath = "SRR1658572_20000_iced.matrix", 
                             BEDpath = "SRR1658572_20000_abs.bed",
                             SAMPLENAME = "Rao et. al.", 
                             COLOR = 'black')
LoadingTime <- proc.time() - ptm

Sanborn_20k <- construct.experiment(ICEDpath = "SRP064914_20000_iced.matrix", 
                             BEDpath = "SRP064914_20000_abs.bed",
                             SAMPLENAME = "Sanborn et. al.", 
                             COLOR = 'red')

Rao_1m <- construct.experiment(ICEDpath = "SRR1658572_1000000_iced.matrix", 
                             BEDpath = "SRR1658572_1000000_abs.bed",
                             SAMPLENAME = "Rao et. al.", 
                             COLOR = 'black')
Sanborn_1m <- construct.experiment(ICEDpath = "SRP064914_1000000_iced.matrix", 
                             BEDpath = "SRP064914_1000000_abs.bed",
                             SAMPLENAME = "Sanborn et. al.", 
                             COLOR = 'red')

# Remove extra chromosomes:
Rao_1m$ABS_all <- Rao_1m$ABS
Rao_1m$ABS <- Rao_1m$ABS_all[!grepl(Rao_1m$ABS_all[,1], pattern = "_", perl = T),]

Sanborn_1m$ABS_all <- Sanborn_1m$ABS
Sanborn_1m$ABS <- Sanborn_1m$ABS_all[!grepl(Sanborn_1m$ABS_all[,1], pattern = "_", perl = T),]

```

# Quality controls

---

### chromosome matrix
```{r chromosomeMatrix, cache=T, cache.lazy=F, eval=T, fig.height=7, fig.width=7, fig.align="center", warning=F, fig.retina=T, dev= c('png', 'pdf')}
chromosomeMatrix(Rao_1m)
chromosomeMatrix(Sanborn_1m)
```

### cisTotal
```{r cisTotal.perChrom, cache=T, cache.lazy=F, eval=T, fig.height=7, fig.width=7, fig.align="center", warning=F, fig.retina=T, dev= c('png', 'pdf')}
cisChrom_Rao <- cisTotal.perChrom(Rao_1m )
cisChrom_Sanborn <- cisTotal.perChrom(Sanborn_1m)
boxplot(cisChrom_Rao,cisChrom_Sanborn, outline = T, names = c("Rao et. al.", "Sanborn et. al."))
unique(Rao_1m $ABS[,1])[cisChrom_Rao < 0.5]
```

```{r cleanUp1, echo = F}
rm(cisChrom_Rao)
rm(cisChrom_Sanborn)
```

### RCP
```{r RCP, cache=T, cache.lazy=F, eval=T, fig.height=7, fig.width=7, fig.align="center", warning=F, fig.retina=T, dev= c('png', 'pdf')}
CHROMS <- unique(Rao_1m$ABS[,1])[!grepl(unique(Rao_1m$ABS[,1]), pattern = "_", perl = T)]
RCP_RaoSanborn <- RCP(list(Rao_1m ,Sanborn_1m), chromsToUse = CHROMS, verbose = F)
visualise.RCP.ggplot(RCPdata = RCP_RaoSanborn)

RCP_RaoSanborn_chr1 <- RCP(list(Rao_1m ,Sanborn_1m), verbose = F,chromsToUse = "chr1")
visualise.RCP.ggplot(RCPdata = RCP_RaoSanborn_chr1, smooth = T)
```

```{r cleanUp2, echo = F }
rm(RCP_RaoSanborn)
```

# Overview tools

---

### matrix plot
```{r matrix, cache=T, cache.lazy=F, eval=T, fig.height=7, fig.width=7, fig.align="center", warning=F, fig.retina=T, dev= c('png', 'pdf')}
CTCF_bw <- "wgEncodeBroadHistoneGm12878CtcfStdSig.bigWig"
CTCF_bed <- read.delim("ENCODE_GM12878_CTCF.bed", h = F)
hic.matrixplot(exp1 = Rao_20k,
               exp2 = Sanborn_20k,chrom = "chr2",start = 175000000, 
               end = 179000000, 
               coplot = "dual", chip = list(NULL, CTCF_bw, CTCF_bed[CTCF_bed[,6] == "+",],CTCF_bed[CTCF_bed[,6] == "-",]), 
               cut.off = 350)
hic.matrixplot(exp1 = Rao_20k,
               exp2 = Sanborn_20k,chrom = "chr2",start = 175000000, 
               end = 179000000, 
               coplot = "diff", chip = list(NULL, CTCF_bw, CTCF_bed[CTCF_bed[,6] == "+",],CTCF_bed[CTCF_bed[,6] == "-",]), 
               cut.off = 100)
```

```{r matrix2, cache=T, cache.lazy=F, eval=T, fig.height=7, fig.width=7, fig.align="center", warning=F, fig.retina=T, dev= c('png', 'pdf')}
hic.matrixplot(exp1 = Rao_1m ,
               exp2 = Sanborn_1m,chrom = "chr2", 
               start = 0, 
               end = 243199373, 
               coplot = "dual", 
               cut.off = 2500)
```

### inter/intra TAD contacts
```{r intra.inter.TAD.contacts, cache=T, cache.lazy=F, eval=T, fig.height=7, fig.width=7, fig.align="center", warning=F, fig.retina=T, dev= c('png', 'pdf'), results=F, message=F}
# Parse BEDPE of HiCseg-TADs
hicsegBEDPE <- read.delim('20k_TADs.bed', h = F)

hicsegBEDPE <-  hicsegBEDPE[hicsegBEDPE$V2 < hicsegBEDPE$V3,]
# 
iiTAD_Rao <- intra.inter.TAD.contacts(TAD = hicsegBEDPE, max.neighbor = 10, exp = Rao_20k)
iiTAD_Sanborn <- intra.inter.TAD.contacts(TAD = hicsegBEDPE, max.neighbor = 10, exp = Sanborn_20k)
```

### differential TAD dotplot
```{r differentialintra.inter.TAD.contactsDOT, cache=T, cache.lazy=F, eval=T, fig.height=7, fig.width=7, fig.align="center", warning=F, fig.retina=T, dev= c('png', 'pdf')}
differential.TAD.dotplot(iiTAD_Rao$hic, iiTAD_Sanborn$hic, ylim = c(-5,5))
```

### differential TAD scatterplot
```{r differentialintra.inter.TAD.contactsSCATTER, cache=T, cache.lazy=F, eval=T, fig.height=7, fig.width=7, fig.align="center", warning=F, fig.retina=T, dev= c('png', 'pdf')}
differential.TAD.scatterplot(iiTAD_Rao$hic, iiTAD_Sanborn$hic)
```

# Aggregation plots

---

### stackR
```{r stackR, cache=T, cache.lazy=F, eval=T, fig.height=7, fig.width=7, fig.align="center", warning=F, fig.retina=T, dev= c('png', 'pdf')}
# Run stackedTAD
stackedTAD.dat.Rao <- stackR(experiment = Rao_20k,tad.bed = hicsegBEDPE, verbose = F,outlierCutOff = 40)
stackedTAD.dat.Sanborn <- stackR(experiment = Sanborn_20k,tad.bed = hicsegBEDPE, verbose = F,outlierCutOff = 40)

# Create list of stackedTAD-results
stackedTADResultList <- list(Rao = stackedTAD.dat.Rao,SanbornKO = stackedTAD.dat.Sanborn)
# Visualise with ggplot
visualise.stackR_V2.ggplot(stackedTADResultList, focus = 2, title = 'Comparing Rao and Sanborn: stacked TAD', zCoef = 1.25)
```
```{r cleanUp3, echo = F }
rm(stackedTAD.dat.Rao)
rm(stackedTAD.dat.Sanborn)
rm(stackedTADResultList)
```

### PESCAn
```{r PESCAn, cache=T, cache.lazy=F, eval=T, fig.height=7, fig.width=7, fig.align="center", warning=F, fig.retina=T, dev= c('png', 'pdf')}
DBsuper <- read.delim("GM12878_DBsuper.bed", h = F)

pesRao <- PESCAn(Rao_20k, bed = DBsuper, size = 200e3)
pesRao.r <- PESCAn(Rao_20k, bed = DBsuper, add=1e6, size = 200e3)

pesSanborn <- PESCAn(Sanborn_20k, bed = DBsuper, size = 200e3)
pesSanborn.r <- PESCAn(Sanborn_20k, bed = DBsuper, add=1e6, size = 200e3)
```
```{r PESCAn2, cache=T, cache.lazy=F, eval=T, fig.height=7, fig.width=7, fig.align="center", warning=F, fig.retina=T, dev= c('png', 'pdf')}
pos <- seq(-200, 200, len=nrow(pesRao))

persp(pos, pos, pesRao/median(pesRao.r),  theta = 30, phi = 30, col="lightblue", shade=0.5, xlab="PE1 dist (kb)", ylab="PE2 dist (kb)", zlab="tag enrichment", nticks=3, ticktype="detailed", main="Rao: superenhancers", border=NA)

persp(pos, pos, pesSanborn/median(pesSanborn.r),  theta = 30, phi = 30, col="lightblue", shade=0.5, xlab="PE1 dist (kb)", ylab="PE2 dist (kb)", zlab="tag enrichment", nticks=3, ticktype="detailed", main="Sanborn: superenhancers", border=NA)
```

### APA
```{r APA, cache=T, cache.lazy=F, eval=T, fig.height=7, fig.width=7, fig.align="center", warning=F, fig.retina=T, dev= c('png', 'pdf')}
# Parse BEDPE of HICCUPS-loops
hiccupsBEDPE <- read.delim('GSE63525_GM12878_primary+replicate_HiCCUPS_looplist.txt', header = T)
hiccupsBEDPE <-  hiccupsBEDPE[!is.na(hiccupsBEDPE[,2]),]
hiccupsBEDPE[,1] <- sub(hiccupsBEDPE[,1], pattern = "^", replacement = 'chr')
hiccupsBEDPE[,4] <- sub(hiccupsBEDPE[,4], pattern = "^", replacement = 'chr')
# Run APA
ptm <- proc.time()
apaResult.Rao <- APA(experiment = Rao_20k, size = 11, loop.bed = hiccupsBEDPE)
RunningTime <- proc.time() - ptm
apaResult.Sanborn <- APA(experiment = Sanborn_20k, size = 11, loop.bed = hiccupsBEDPE)

# Create list of APA-results
apaResultList <- list(Rao = apaResult.Rao$APA, Sanborn = apaResult.Sanborn$APA)

# Visualise APA with ggplot
visualise.APA.ggplot(apaResultList, title = 'Comparing Rao and Sanborn: APA',resolution = Rao_20k$RES, focus = 1)

barplot(c((1.4708),(LoadingTime[3]+RunningTime[3])/60), ylim = c(0,1.6), ylab = 'Time (minutes)', main = "Timing APA", names.arg = c("Juicer","GENOVA"))
abline(h = 1.4708, lty = 3)
```
```{r plotAPA, echo = F}


# Visualise APA with base R
#visualise.APA(apaResultList, title = 'Comparing Rao and SanbornKO: APA', focus = 1)
```
```{r cleanUp4, echo = F }
rm(apaResult.Rao)
rm(apaResult.Sanborn)
rm(apaResultList)
```
### virtual 4C
```{r virt4C, cache=T, cache.lazy=F, eval=F, echo = F, fig.height=7, fig.width=7, fig.align="center", warning=F, fig.retina=T, dev= c('png', 'pdf')}
# Run virt4C
virt4Cdat <- virtual.4C(experiment = Rao_20k, loop.bed = hiccupsBEDPE)

# Visualise with base R
visualise.virtual.4C(virt4Cdat)
```
