---
title: "GENOVA: expore the Hi-C"
author: "Robin H. van der Weide & Elzo de Wit"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## To do:
1. Save all iterations in APA to a list and that reduce. This will save more time.
1. Add a per-loop plotting function in virt4C. Per-loop can be done at the moment by supplying only one row in `loop.bed`.

```{r}
library("GENOVA")
```

## Loading data
```{r loading, eval = F, message=FALSE}
WT <- construct.experiment(ICEDpath = '~/Desktop/myExperiment/WT_10000_iced.matrix', 
                          BEDpath = '~/Desktop/myExperiment/WT_10000_abs.bed',
                          SAMPLENAME = "WT", 
                          COLOR = 'blue')

DKO <- construct.experiment(ICEDpath = '~/Desktop/myExperiment/DKO_10000_iced.matrix', 
                           BEDpath = '~/Desktop/myExperiment/WT_10000_abs.bed',
                           SAMPLENAME = "DKO", 
                           COLOR = 'red')

# Parse BEDPE of HICCUPS-loops
hiccupsBEDPE <- read.bedpe('~/MEGA/Work/PhD/projects/HiCvis/DKO.hiccups')

# Parse BEDPE of HiCseg-TADs
hicsegBEDPE <- read.delim('~/Desktop/myExperiment/DKO.HiCseg', h = F)
```

## Aggegrate peak analysis
```{r APA, eval = F,message=FALSE, fig.align='center'}
# Run APA
apaResult.WT <- APA(experiment = WT, loop.bed = hiccupsBEDPE)
apaResult.DKO <- APA(experiment = DKO, loop.bed = hiccupsBEDPE)

# Create list of APA-results
apaResultList <- list(WT = apaResult.WT, DKO = apaResult.DKO)

# Visualise APA with ggplot
visualise.APA.ggplot(apaResultList, title = 'Comparing WT and DKO: APA')
```

## Virtual 4C
```{r 4C, eval = F,message=FALSE, fig.align='center'}
# Run virt4C
virt4Cdat <- virtual.4C(experiment = WT, loop.bed = hiccupsBEDPE)

# Visualise with base R
visualise.virtual.4C(virt4Cdat)
```

## Stacked TAD analysis
```{r stackedTAD, eval=F, fig.align='center', fig.width=9, message=FALSE}
# # Run stackedTAD
stackedTAD.dat.WT <- stackR(experiment = WT,tad.bed = hicsegBEDPE, verbose = F,outlierCutOff = 40)
stackedTAD.dat.DKO <- stackR(experiment = DKO,tad.bed = hicsegBEDPE, verbose = F,outlierCutOff = 40)

# Create list of stackedTAD-results
stackedTADResultList <- list(WT = stackedTAD.dat.WT,DKO = stackedTAD.dat.DKO)
```


```{r stackedTADvis, eval=F, fig.align='center', fig.width=5,fig.height=5, message=FALSE}
# Visualise with ggplot
visualise.stackR.ggplot(stackedTADResultList, focus = 1, title = 'Comparing WT and DKO: stacked TAD')
```

## Relative contact probability
```{r RCP, eval =F ,message=FALSE, fig.align='center'}
# Run RCP
dat.RCP <- RCP(list(WT, DKO), chromsToUse = c('chr19','chr18'), verbose = F)

# Visualise with ggplot
visualise.RCP.ggplot(dat.RCP)
```
