#' @keywords internal
"_PACKAGE"

#' @import utils graphics stats grDevices
NULL

utils::globalVariables(c('.',
                         LETTERS[1:5],
                         'colour', 
                         'samplename',
                         'SUM', 
                         'DI',
                         'distance',
                         'value', 
                         'variable',
                         'experiment',
                         'rowIDX',
                         'score',
                         'mid', 
                         'P',
                         'pos',
                         'left',
                         'right',
                         'delta',
                         'values',
                         'ins',
                         'type',
                         'strength',
                         'feat',
                         'mu',
                         'ord',
                         'q1',
                         'q2',
                         'id',
                         'idx1',
                         'idx2',
                         'uni5p',
                         'i',
                         'j',
                         'term1', 'term2',
                         paste0('V',1:5),
                         "x", 
                         'y',
                         'J', 
                         'unLog',
                         'experiment',
                         'ymin',
                         '..expnames', 
                         'position',
                         'insulation',
                         'chromosome',
                         "part",
                         'rcp',
                         'panel',
                         'dir_index',
                         "start",
                         'index',
                         'obs.exp.matrix',
                         'obsexp', 
                         'region', 
                         'signal',
                         'chrom', 
                         'chr', 
                         'bin',
                         'binned'))

